### PR TITLE
Docker-compose setup with database + phpmyadmin

### PR DESCRIPTION
**Pull request by rml1997**

### CODE REVIEW

**Comment by linusnorton** [comment]
Thanks for the PR, I'm happy to accept it. But I'm wondering if it's best to map port 3306 to something different? I already have mariadb running on my host so it would conflict.

**Comment by rml1997** [comment]
I'm not sure what the best thing to do here would be. It would be possible to change the port, hide the network from the host, or include instructions for one or both of those things. It just depends what the user intends to do with the project I guess. Publishing the default port allows the use of external tools. You can set the database port via "docker-compose run -p 3307:3306 db" but I'm not sure how to set dtd2mysql to look at the other port?

**Comment by linusnorton** [comment]
We should be able to add `DATABASE_PORT=3307` in the .env file

**Comment by rml1997** [comment]
container.ts doesn't seem to support this currently

**Comment by linusnorton** [comment]
I've pushed a change to master so it does now

**Pull request closed without merging**
